image: gitpod/workspace-base:latest

tasks:
  - command: |-
      curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      rm kubectl
      curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64
      sudo install -o root -g root -m 0755 kind /usr/local/bin/kind
      rm kind
      curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      sudo install -o root -g root -m 0755 minikube-linux-amd64 /usr/local/bin/minikube
      rm minikube-linux-amd64
      curl -LO https://github.com/derailed/k9s/releases/download/v0.25.18/k9s_Linux_x86_64.tar.gz
      tar xzf k9s_Linux_x86_64.tar.gz k9s
      sudo install -o root -g root -m 0755 k9s /usr/local/bin/k9s
      rm k9s k9s_Linux_x86_64.tar.gz
      curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      k3d cluster create
